services:
  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/app
    environment:
      APP_ENV: dev
      PHP_IDE_CONFIG: serverName=php-fpm
