initial-service-host: "hetzner-eu-02"
d2c-service-config:
  type: "docker"
  image: "ghcr.io/rollun-lc/service-utils/service-utils/prod"
  version: "latest"
  name: "utils-php"
  description: "Service utils php"
  project: "Utils"
  ports:
    - value: 9000
      protocol: "TCP"
  env:
    - name: "APP_DEBUG"
      value: "false"
