openapi: 3.0.0
info:
  version: "1"
  title: "Utility"
  description: "Provides utility endpoints for various calculations"
servers:
  - url: http://utils/openapi/Utility/v1
  - url: http://host.docker.internal:8091/openapi/Utility/v1
tags:
  - name: "GetZone"
    description: "Endpoints related to shipping zone calculations between ZIP codes."
paths:
  /getZone:
    get:
      summary: "Retrieve shipping zone between two ZIP codes"
      description: "Returns the shipping zone based on the provided origin (zipFrom) and destination (zipTo) ZIP codes."
      tags:
        - "GetZone"
      parameters:
        - name: zipFrom
          in: query
          required: true
          description: "The ZIP code of the origin location"
          schema:
            type: string
            example: "90210"
        - name: zipTo
          in: query
          required: true
          description: "The ZIP code of the destination location"
          schema:
            type: string
            example: "10001"
        - name: source
          in: query
          required: false
          description: "Optional parameter to specify the data source."
          schema:
            type: string
            default: "USPS"
            example: "USPS"
            enum:
              - "USPS"
      responses:
        '200':
          description: "Successfully calculated the shipping zone."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetZoneResult"
        '500':
          description: "Internal server error."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResult"

components:
  schemas:
    ErrorResult:
      type: object
      description: "Error response containing messages"
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"

    Message:
      type: object
      description: "Detailed error message"
      properties:
        level:
          type: string
          example: error
          enum:
            - emergency
            - alert
            - critical
            - error
            - warning
            - notice
            - info
          description: "Severity level of the message"
        type:
          type: string
          enum:
            - UNDEFINED
            - LOGGER_MESSAGE
          description: "Type of the message"
        text:
          type: string
          example: "Invalid data"
          description: "Human-readable error message"

    SuccessResult:
      type: object
      description: "Basic structure for a successful response, including potential messages"
      properties:
        data:
          type: object
          description: "Data returned in the successful response"
        messages:
          type: array
          items:
            $ref: "#/components/schemas/Message"
    GetZoneResult:
      allOf:
        - $ref: '#/components/schemas/SuccessResult'
      description: "Successful response for the GetZone endpoint"
      properties:
        data:
          $ref: '#/components/schemas/GetZoneResultData'
    GetZoneResultData:
      type: object
      description: "Details of the shipping zone calculation"
      properties:
        zipFrom:
          type: string
          description: "Origin ZIP code"
          example: "90210"
        zipTo:
          type: string
          description: "Destination ZIP code"
          example: "10001"
        zone:
          type: integer
          description: "Calculated shipping zone"
          example: 5
